apiVersion: v1
kind: Secret
metadata:
  name: crud-app-tls-and-db  # Matches ingress.tls.secretName
  labels:
    {{- include "crud-app-ext-pg.labels" . | nindent 4 }}
type: kubernetes.io/tls  # For TLS certs
data:
  tls.crt: {{ .Files.Get "certs/tls.crt" | b64enc }}  # From certs/ folder
  tls.key: {{ .Files.Get "certs/tls.key" | b64enc }}   # From certs/ folder
  database: {{ "mainschema" | b64enc }}               # Hardcoded for now
  username: {{ "postgres" | b64enc }}                 # Hardcoded for now
  password: {{ "admin" | b64enc }}                    # Hardcoded for now