apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  username: cm9vdA==   # base64 encoded 'root'
  password: cm9vdA==   # base64 encoded 'root'


# URL https://www.base64encode.org/ 
# Pass thecreds with default setting in website and take the value
# and paste it 

#OR
#┌──(ashu㉿kali)-[~/Desktop/code/k8s/practise]
#└─$ echo -n "root" | base64

#cm9vdA==
