apiVersion: v1
kind: Secret
metadata:
  name: restapi-tls  # Matches ingress.tls.secretName
  labels:
    {{- include "restapiingresshttps.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "certs/tls.crt" | b64enc }}  # Base64-encoded cert
  tls.key: {{ .Files.Get "certs/tls.key" | b64enc }}  # Base64-encoded key